label: Cdmx ageb
centroids_file: cdmx-ageb-centroids.csv
altids_file:
level: ageb_cdmx
id_format: "%02d"
code_cols: ["id", "codigo"]
name_cols: ["name", "ageb"]
topojson:
  label: CDMX AGEB
  basename: cdmx-ageb
  scope: ageb_cdmx
  geographyName: name
  geographyId: id
  path: cdmx-ageb.topojson
  projections:
    mercator:
      center: [-102.5, 25]
      rotate: [0, 0]
      scale: 1.7
      translate: [0,0]
    equirectangular:
      center: [-102.5, 25]
      rotate: [0, 0]
      scale: 1.7
      translate: [0,0]
    albers:
      scale: 1.7
      rotate: [100, 0]
      center: [0, 25]
      parallels: [29.5, 45.5]
      translate: [0,0]
