label: World countries
centroids_file: world_countries-centroids.csv
altnames_file: world_countries-altnames.csv
altids_file: 
regions_file: world_countries-regions.csv
topojson:
  scope: XXX
  geographyName: name
  geographyId: id
  path: world_countries.topojson
projections:
  mercator:
    name: mercator
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
  equirectangular:
    name: mercator
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
