label: Guatemala departaments
centroids_file: gtm_municipalities-centroids.csv
altids_file: 
altnames_file: gtm_municipalities-altnames.csv
level: ADM2
regions: 
parent_map_name: gtm_departments
id_format: "%04d"
topojson:
  scope: XXX
  geographyName: name
  geographyId: id
  path: gtm_municipalities.topojson
projections:
  mercator:
    name: mercator
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
  equirectangular:
    name: mercator
    center: [-90.30, 16.22]
    rotate: [0, 0]
    scale: 5.5
    translate: [0,0]
